In [1]:
import torch

In [2]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [3]:
i = torch.ones((5,3),dtype = torch.int16)
print(i)
print(i.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
torch.int16


In [5]:
ones = torch.ones(5,3)
print(ones)

twos = torch.ones(5,3) * 2
print(twos)

print(ones+twos)
print(twos.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
torch.Size([5, 3])


In [47]:
r=(torch.rand(3,3)-0.5) *2
print(r)

tensor([[ 0.7061, -0.6323, -0.3713],
        [-0.3184, -0.7358,  0.5299],
        [ 0.8270,  0.9667,  0.3733]])


In [48]:
print(torch.abs(r))

tensor([[0.7061, 0.6323, 0.3713],
        [0.3184, 0.7358, 0.5299],
        [0.8270, 0.9667, 0.3733]])


In [49]:
print(torch.asin(r))

tensor([[ 0.7839, -0.6846, -0.3804],
        [-0.3241, -0.8269,  0.5585],
        [ 0.9737,  1.3121,  0.3826]])


In [50]:
print(torch.det(r))

tensor(-1.0196)


In [51]:
print(torch.svd(r))

torch.return_types.svd(
U=tensor([[ 0.1353, -0.9872,  0.0840],
        [ 0.5055,  0.1417,  0.8511],
        [-0.8522, -0.0727,  0.5182]]),
S=tensor([1.4983, 1.0088, 0.6745]),
V=tensor([[-0.5140, -0.7953,  0.3215],
        [-0.8552,  0.4458, -0.2646],
        [-0.0671,  0.4109,  0.9092]]))


In [52]:
print(torch.std_mean(r))

(tensor(0.6630), tensor(0.1495))


In [53]:
print(torch.max(r))

tensor(0.9667)


In [54]:
print(torch.sum(r))

tensor(1.3451)


In [55]:
r[0]

tensor([ 0.7061, -0.6323, -0.3713])

In [57]:
print(torch.sum(r[0]))
print(torch.sum(r[1]))
print(torch.sum(r[2]))
print(torch.sum(r))

tensor(-0.2976)
tensor(-0.5243)
tensor(2.1670)
tensor(1.3451)


In [61]:
sgbd = torch.zeros((500,500), dtype=torch.int8)
sgbd

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.int8)

In [66]:
sgbd[0][1] = 1
sgbd[1][0] = 1
sgbd[1][2] = 1
print(sgbd[0])

tensor([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,